// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// greet.cpp
void greet(cpp11::strings name);
extern "C" SEXP _notiondb_greet(SEXP name) {
  BEGIN_CPP11
    greet(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(name));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_notiondb_greet", (DL_FUNC) &_notiondb_greet, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_notiondb(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
